---
all:
        children:
                controllPlane:
                        hosts:
                                CP_Node1:
                worker:
                        hosts:
                                Worker_Node1:
