---
all:
        children:
                controllPlane:
                        hosts:
                                KC1:
                initWorker:
                        hosts:
                                KW1:
                                KW2:
                                KW3:
                                KW4:
                                KW5:
                                KW6:
                addWorker:
                        hosts:
                                KW7:
                                KW8:
                                KW9:
                                KW10:

